rm -rf target/
rm -rf project/project/
rm -rf project/target/
rm -rf backend/target/
rm -rf frontend/target/
rm -rf shared/.js/target/
rm -rf shared/.jvm/target/
rm -rf ~/.ivy2
rm -rf ~/.coursier
rm -rf ~/.sbt/1.0/plugins/project/
rm -rf ~/.sbt/1.0/plugins/target/
